-- VHDL Entity tb_lib.tb_register_controller.symbol
--
-- Created:
--          by - kayra.UNKNOWN (ROOPE-PC)
--          at - 11:35:45 08/24/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_register_controller IS
-- Declarations

END tb_register_controller ;

--
-- VHDL Architecture tb_lib.tb_register_controller.struct
--
-- Created:
--          by - roope.UNKNOWN (ROOPE-PC)
--          at - 15:04:56 21.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_register_controller IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL bit_out  : std_logic;
   SIGNAL channel  : std_logic_vector(7 DOWNTO 0);
   SIGNAL clk      : std_logic;
   SIGNAL do_tx    : std_logic;
   SIGNAL lat      : std_logic;
   SIGNAL pixdata  : std_logic_vector(23 DOWNTO 0);
   SIGNAL rst_n    : std_logic;
   SIGNAL rx_ready : std_logic;
   SIGNAL xr       : std_logic_vector(7 DOWNTO 0);
   SIGNAL yr       : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c5_t3_register_bank_to_serial_data
   PORT (
      clk      : IN     std_logic ;
      color    : IN     std_logic_vector (23 DOWNTO 0);
      rst      : IN     std_logic ;
      rx_ready : IN     std_logic ;
      bit_out  : OUT    std_logic ;
      channel  : OUT    std_logic_vector (7 DOWNTO 0);
      do_tx    : OUT    std_logic ;
      lat      : OUT    std_logic ;
      x        : OUT    std_logic_vector (7 DOWNTO 0);
      y        : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT register_controller_tester
   PORT (
      bit_out  : IN     std_logic ;
      channel  : IN     std_logic_vector (7 DOWNTO 0);
      do_tx    : IN     std_logic ;
      lat      : IN     std_logic ;
      x        : IN     std_logic_vector (7 DOWNTO 0);
      y        : IN     std_logic_vector (7 DOWNTO 0);
      clk      : OUT    std_logic ;
      pixdata  : OUT    std_logic_vector (23 DOWNTO 0);
      rst_n    : OUT    std_logic ;
      rx_ready : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c5_t3_register_bank_to_serial_data USE ENTITY alien_game_lib.c5_t3_register_bank_to_serial_data;
   FOR ALL : register_controller_tester USE ENTITY tb_lib.register_controller_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : c5_t3_register_bank_to_serial_data
      PORT MAP (
         clk      => clk,
         color    => pixdata,
         rst      => rst_n,
         rx_ready => rx_ready,
         bit_out  => bit_out,
         channel  => channel,
         do_tx    => do_tx,
         lat      => lat,
         x        => xr,
         y        => yr
      );
   U_1 : register_controller_tester
      PORT MAP (
         bit_out  => bit_out,
         channel  => channel,
         do_tx    => do_tx,
         lat      => lat,
         x        => xr,
         y        => yr,
         clk      => clk,
         pixdata  => pixdata,
         rst_n    => rst_n,
         rx_ready => rx_ready
      );

END struct;
