-- VHDL Entity alien_game_lib.alien_game_top.symbol
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-707-SPC)
--          at - 12:28:59 28.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY alien_game_top IS
   PORT( 
      btn     : IN     std_logic_vector (3 DOWNTO 0);
      clk     : IN     std_logic;
      rst_n   : IN     std_logic;
      channel : OUT    std_logic_vector (7 DOWNTO 0);
      lat     : OUT    std_logic;
      s_clk   : OUT    std_logic;
      s_rst   : OUT    std_logic;
      s_sda   : OUT    std_logic;
      sb      : OUT    std_logic
   );

-- Declarations

END alien_game_top ;

--
-- VHDL Architecture alien_game_lib.alien_game_top.struct
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-707-SPC)
--          at - 12:28:59 28.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF alien_game_top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL BGR_color  : std_logic_vector(23 DOWNTO 0);
   SIGNAL frame_done : std_logic;
   SIGNAL w_rdy      : std_logic;
   SIGNAL write      : std_logic;
   SIGNAL x_coord    : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord    : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT display_controller_v2
   PORT (
      clk           : IN     std_logic ;
      frame_written : IN     std_logic ;
      pixd_in       : IN     std_logic_vector (23 DOWNTO 0);
      rst_n         : IN     std_logic ;
      write         : IN     std_logic ;
      xw            : IN     std_logic_vector (7 DOWNTO 0);
      yw            : IN     std_logic_vector (7 DOWNTO 0);
      channel       : OUT    std_logic_vector (7 DOWNTO 0);
      lat           : OUT    std_logic ;
      s_clk         : OUT    std_logic ;
      s_rst         : OUT    std_logic ;
      s_sda         : OUT    std_logic ;
      sb            : OUT    std_logic ;
      w_rdy         : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT game_logic
   PORT (
      btn         : IN     std_logic_vector (3 DOWNTO 0);
      clk         : IN     std_logic ;
      rst_n       : IN     std_logic ;
      write_ready : IN     std_logic ;
      BGR_color   : OUT    std_logic_vector (23 DOWNTO 0);
      frame_done  : OUT    std_logic ;
      write       : OUT    std_logic ;
      x_coord     : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : display_controller_v2 USE ENTITY alien_game_lib.display_controller_v2;
   FOR ALL : game_logic USE ENTITY alien_game_lib.game_logic;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : display_controller_v2
      PORT MAP (
         clk           => clk,
         frame_written => frame_done,
         pixd_in       => BGR_color,
         rst_n         => rst_n,
         write         => write,
         xw            => x_coord,
         yw            => y_coord,
         channel       => channel,
         lat           => lat,
         s_clk         => s_clk,
         s_rst         => s_rst,
         s_sda         => s_sda,
         sb            => sb,
         w_rdy         => w_rdy
      );
   U_1 : game_logic
      PORT MAP (
         btn         => btn,
         clk         => clk,
         rst_n       => rst_n,
         write_ready => w_rdy,
         BGR_color   => BGR_color,
         frame_done  => frame_done,
         write       => write,
         x_coord     => x_coord,
         y_coord     => y_coord
      );

END struct;
