-- VHDL Entity alien_game_lib.c1_t3_hello_led.symbol
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-719-SPC)
--          at - 11:38:15 26.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t3_hello_led IS
   PORT( 
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c1_t3_hello_led ;

--
-- VHDL Architecture alien_game_lib.c1_t3_hello_led.struct
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-719-SPC)
--          at - 11:38:15 26.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c1_t3_hello_led IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   color_BGR <= x"FF0806";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   x_coord <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   y_coord <= "01000000";

   -- Instance port mappings.

END struct;
