-- VHDL Entity alien_game_lib.c2_t1_incrementer.symbol
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-719-SPC)
--          at - 08:21:34  3.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_incrementer IS
   PORT( 
      input  : IN     std_logic_vector (2 DOWNTO 0);
      result : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END c2_t1_incrementer ;

--
-- VHDL Architecture alien_game_lib.c2_t1_incrementer.struct
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-719-SPC)
--          at - 08:32:53  3.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t1_incrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL carry  : std_logic;
   SIGNAL carry1 : std_logic;
   SIGNAL dout   : std_logic;


   -- Component Declarations
   COMPONENT c1_t1_halfAdder
   PORT (
      sw0   : IN     std_logic ;
      sw1   : IN     std_logic ;
      carry : OUT    std_logic ;
      sum   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_t1_halfAdder USE ENTITY alien_game_lib.c1_t1_halfAdder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   dout <= '1';

   -- Instance port mappings.
   U_2 : c1_t1_halfAdder
      PORT MAP (
         sw0   => dout,
         sw1   => input(0),
         carry => carry,
         sum   => result(0)
      );
   U_3 : c1_t1_halfAdder
      PORT MAP (
         sw0   => carry,
         sw1   => input(1),
         carry => carry1,
         sum   => result(1)
      );
   U_4 : c1_t1_halfAdder
      PORT MAP (
         sw0   => carry1,
         sw1   => input(2),
         carry => OPEN,
         sum   => result(2)
      );

END struct;
