-- VHDL Entity alien_game_lib.c2_t7_alien_direction_controller.symbol
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-717-SPC)
--          at - 09:26:42 10.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t7_alien_direction_controller IS
   PORT( 
      clk          : IN     std_logic;
      rst_n        : IN     std_logic;
      x_coordinate : IN     std_logic_vector (7 DOWNTO 0);
      direction    : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END c2_t7_alien_direction_controller ;

--
-- VHDL Architecture alien_game_lib.c2_t7_alien_direction_controller.struct
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-717-SPC)
--          at - 09:26:42 10.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t7_alien_direction_controller IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL d     : std_logic;
   SIGNAL din1  : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL q     : std_logic;
   SIGNAL q1    : std_logic;
   SIGNAL qb    : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_14' of 'adff'
   SIGNAL mw_U_14reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_4' of 'adff'
   q <= mw_U_4reg_cval;
   qb <= NOT(mw_U_4reg_cval);
   u_4seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_4reg_cval <= '1';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_4reg_cval <= d;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_14' of 'adff'
   q1 <= mw_U_14reg_cval;
   u_14seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_14reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_14reg_cval <= x_coordinate(0);
      END IF;
   END PROCESS u_14seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'and'
   dout5 <= NOT(x_coordinate(0)) AND q;

   -- ModuleWare code(v1.12) for instance 'U_13' of 'and'
   dout4 <= qb AND NOT(x_coordinate(7));

   -- ModuleWare code(v1.12) for instance 'U_15' of 'and'
   dout1 <= x_coordinate(7) AND qb;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'buff'
   direction <= din1;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'merge'
   din1 <= dout4 & dout5;

   -- ModuleWare code(v1.12) for instance 'U_16' of 'or'
   d <= dout OR dout1;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'xor'
   dout <= q XOR q1;

   -- Instance port mappings.

END struct;
