-- VHDL Entity alien_game_lib.c2_t7_basic_alien.symbol
--
-- Created:
--          by - roope.UNKNOWN (DESKTOP-N94PERP)
--          at - 16:45:47 12.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t7_basic_alien IS
   PORT( 
      clk            : IN     std_logic;
      enable         : IN     std_logic;
      hit            : IN     std_logic;
      rst_n          : IN     std_logic;
      Alien_color    : OUT    std_logic_vector (23 DOWNTO 0);
      X_coordinate   : OUT    std_logic_vector (7 DOWNTO 0);
      Y_coordinate   : OUT    std_logic_vector (7 DOWNTO 0);
      alien_defeated : OUT    std_logic
   );

-- Declarations

END c2_t7_basic_alien ;

--
-- VHDL Architecture alien_game_lib.c2_t7_basic_alien.struct
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-713-SPC)
--          at - 10:58:40 30.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t7_basic_alien IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL data_out  : std_logic_vector(7 DOWNTO 0);
   SIGNAL data_out1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din1      : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1     : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout10    : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout2     : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout8     : std_logic;
   SIGNAL dout9     : std_logic_vector(23 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL X_coordinate_internal   : std_logic_vector (7 DOWNTO 0);
   SIGNAL alien_defeated_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_17' of 'adff'
   SIGNAL mw_U_17reg_cval : std_logic;

   -- Component Declarations
   COMPONENT c2_t3_left_shifter
   PORT (
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c2_t4_right_shifter
   PORT (
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c2_t7_alien_direction_contoller_v2
   PORT (
      clk       : IN     std_logic ;
      rst_n     : IN     std_logic ;
      x_coord   : IN     std_logic_vector (7 DOWNTO 0);
      direction : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t3_left_shifter USE ENTITY alien_game_lib.c2_t3_left_shifter;
   FOR ALL : c2_t4_right_shifter USE ENTITY alien_game_lib.c2_t4_right_shifter;
   FOR ALL : c2_t7_alien_direction_contoller_v2 USE ENTITY alien_game_lib.c2_t7_alien_direction_contoller_v2;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   X_coordinate_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= "00000100";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= dout;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_17' of 'adff'
   alien_defeated_internal <= mw_U_17reg_cval;
   u_17seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_17reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_17reg_cval <= dout8;
      END IF;
   END PROCESS u_17seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout2 <= "00";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   Y_coordinate <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_12' of 'constval'
   dout9 <= x"ff00ff";

   -- ModuleWare code(v1.12) for instance 'U_20' of 'constval'
   dout10 <= x"000000";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'mux'
   u_5combo_proc: PROCESS(X_coordinate_internal, data_out, data_out1, 
                          dout1)
   BEGIN
      CASE dout1 IS
      WHEN "00" => dout <= X_coordinate_internal;
      WHEN "01" => dout <= data_out;
      WHEN "10" => dout <= data_out1;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_5combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(dout2, din1, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => dout1 <= dout2;
      WHEN '1' => dout1 <= din1;
      WHEN OTHERS => dout1 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_6combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_19' of 'mux'
   u_19combo_proc: PROCESS(dout9, dout10, alien_defeated_internal)
   BEGIN
      CASE alien_defeated_internal IS
      WHEN '0' => Alien_color <= dout9;
      WHEN '1' => Alien_color <= dout10;
      WHEN OTHERS => Alien_color <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_19combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_18' of 'or'
   dout8 <= hit OR alien_defeated_internal;

   -- Instance port mappings.
   U_1 : c2_t3_left_shifter
      PORT MAP (
         data_in  => X_coordinate_internal,
         data_out => data_out1
      );
   U_2 : c2_t4_right_shifter
      PORT MAP (
         data_in  => X_coordinate_internal,
         data_out => data_out
      );
   U_4 : c2_t7_alien_direction_contoller_v2
      PORT MAP (
         clk       => clk,
         rst_n     => rst_n,
         x_coord   => X_coordinate_internal,
         direction => din1
      );

   -- Implicit buffered output assignments
   X_coordinate   <= X_coordinate_internal;
   alien_defeated <= alien_defeated_internal;

END struct;
