-- VHDL Entity alien_game_lib.c2_t3_left_shifter.symbol
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-719-SPC)
--          at - 08:41:34  3.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t3_left_shifter IS
   PORT( 
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t3_left_shifter ;

--
-- VHDL Architecture alien_game_lib.c2_t3_left_shifter.struct
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-719-SPC)
--          at - 08:55:20  3.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t3_left_shifter IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0 : std_logic;
   SIGNAL din1 : std_logic;
   SIGNAL din2 : std_logic;
   SIGNAL din3 : std_logic;
   SIGNAL din4 : std_logic;
   SIGNAL din5 : std_logic;
   SIGNAL din6 : std_logic;
   SIGNAL din7 : std_logic;
   SIGNAL dout : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   din3 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_9' of 'constval'
   din0 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_10' of 'constval'
   din1 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_11' of 'constval'
   din2 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_12' of 'constval'
   din4 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_13' of 'constval'
   din5 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_14' of 'constval'
   din6 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_15' of 'constval'
   din7 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_16' of 'constval'
   dout <= '0';

   -- ModuleWare code(v1.12) for instance 'U_17' of 'inv'

   -- ModuleWare code(v1.12) for instance 'U_0' of 'or'
   data_out(0) <= din0 OR dout;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'or'
   data_out(1) <= din1 OR data_in(0);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'or'
   data_out(2) <= din2 OR data_in(1);

   -- ModuleWare code(v1.12) for instance 'U_3' of 'or'
   data_out(3) <= din3 OR data_in(2);

   -- ModuleWare code(v1.12) for instance 'U_4' of 'or'
   data_out(4) <= din4 OR data_in(3);

   -- ModuleWare code(v1.12) for instance 'U_5' of 'or'
   data_out(5) <= din5 OR data_in(4);

   -- ModuleWare code(v1.12) for instance 'U_6' of 'or'
   data_out(6) <= din6 OR data_in(5);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'or'
   data_out(7) <= din7 OR data_in(6);

   -- Instance port mappings.

END struct;
