-- VHDL Entity alien_game_lib.c3_t4_4_to_2_encoder.symbol
--
-- Created:
--          by - roope.UNKNOWN (DESKTOP-N94PERP)
--          at - 14:52:06 22.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t4_4_to_2_encoder IS
   PORT( 
      in_1    : IN     std_logic;
      in_2    : IN     std_logic;
      in_3    : IN     std_logic;
      in_4    : IN     std_logic;
      bus_out : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END c3_t4_4_to_2_encoder ;

--
-- VHDL Architecture alien_game_lib.c3_t4_4_to_2_encoder.tbl
--
-- Created:
--          by - roope.UNKNOWN (DESKTOP-N94PERP)
--          at - 14:52:06 22.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF c3_t4_4_to_2_encoder IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(in_1, in_2, in_3, in_4)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (in_1 = '0') AND (in_2 = '0') AND (in_3 = '0') AND (in_4 = '0') THEN
         bus_out <= "00";
      ELSIF (in_1 = '1') AND (in_2 = '0') AND (in_3 = '0') AND (in_4 = '0') THEN
         bus_out <= "00";
      ELSIF (in_1 = '0') AND (in_2 = '1') AND (in_3 = '0') AND (in_4 = '0') THEN
         bus_out <= "01";
      ELSIF (in_1 = '0') AND (in_2 = '0') AND (in_3 = '1') AND (in_4 = '0') THEN
         bus_out <= "10";
      ELSIF (in_1 = '0') AND (in_2 = '0') AND (in_3 = '0') AND (in_4 = '1') THEN
         bus_out <= "11";
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
