-- VHDL Entity alien_game_lib.c3_t4_bullet_flight_modelling_v2.symbol
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-708-SPC)
--          at - 11:54:32  1.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t4_bullet_flight_modelling_v2 IS
   PORT( 
      btn            : IN     std_logic;
      clk            : IN     std_logic;
      enable         : IN     std_logic;
      gun_x_coord    : IN     std_logic_vector (7 DOWNTO 0);
      rst_n          : IN     std_logic;
      bullet_x_coord : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y_coord : OUT    std_logic_vector (7 DOWNTO 0);
      color          : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c3_t4_bullet_flight_modelling_v2 ;

--
-- VHDL Architecture alien_game_lib.c3_t4_bullet_flight_modelling_v2.struct
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-708-SPC)
--          at - 11:54:32  1.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c3_t4_bullet_flight_modelling_v2 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL data_out : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2    : std_logic;
   SIGNAL dout4    : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout5    : std_logic;
   SIGNAL set      : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL bullet_x_coord_internal : std_logic_vector (7 DOWNTO 0);
   SIGNAL bullet_y_coord_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'x_coord' of 'adff'
   SIGNAL mw_x_coordreg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'y_coord' of 'adff'
   SIGNAL mw_y_coordreg_cval : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT c2_t4_right_shifter
   PORT (
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t4_right_shifter USE ENTITY alien_game_lib.c2_t4_right_shifter;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'x_coord' of 'adff'
   bullet_x_coord_internal <= mw_x_coordreg_cval;
   x_coordseq_proc: PROCESS (clk, rst_n, dout5)
   BEGIN
      IF (rst_n = '0') THEN
         mw_x_coordreg_cval <= "00000000";
      ELSIF (dout5 = '1') THEN
         mw_x_coordreg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_x_coordreg_cval <= dout4;
      END IF;
   END PROCESS x_coordseq_proc;

   -- ModuleWare code(v1.12) for instance 'y_coord' of 'adff'
   bullet_y_coord_internal <= mw_y_coordreg_cval;
   y_coordseq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_y_coordreg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         IF (set = '1') THEN
            mw_y_coordreg_cval <= "00100000";
         ELSE
            mw_y_coordreg_cval <= dout;
         END IF;
      END IF;
   END PROCESS y_coordseq_proc;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'and'
   set <= btn AND dout2 AND enable;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'and'
   dout5 <= NOT(set) AND dout2;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   color <= x"ffffff";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(bullet_y_coord_internal, data_out, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => dout <= bullet_y_coord_internal;
      WHEN '1' => dout <= data_out;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'mux'
   u_8combo_proc: PROCESS(bullet_x_coord_internal, gun_x_coord, set)
   BEGIN
      CASE set IS
      WHEN '0' => dout4 <= bullet_x_coord_internal;
      WHEN '1' => dout4 <= gun_x_coord;
      WHEN OTHERS => dout4 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_8combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'tor'
   dout2 <= NOT(bullet_y_coord_internal(0) OR bullet_y_coord_internal(1)
            OR bullet_y_coord_internal(2) OR bullet_y_coord_internal(3)
            OR bullet_y_coord_internal(4) OR bullet_y_coord_internal(5)
            OR bullet_y_coord_internal(6) OR bullet_y_coord_internal(7));

   -- Instance port mappings.
   U_3 : c2_t4_right_shifter
      PORT MAP (
         data_in  => bullet_y_coord_internal,
         data_out => data_out
      );

   -- Implicit buffered output assignments
   bullet_x_coord <= bullet_x_coord_internal;
   bullet_y_coord <= bullet_y_coord_internal;

END struct;
