-- VHDL Entity alien_game_lib.c4_t1_hit_detector.symbol
--
-- Created:
--          by - roope.UNKNOWN (DESKTOP-N94PERP)
--          at - 17:44:20 29.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_hit_detector IS
   PORT( 
      alien_x_coord  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y_coord  : IN     std_logic_vector (7 DOWNTO 0);
      bullet_x_coord : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y_coord : IN     std_logic_vector (7 DOWNTO 0);
      clk            : IN     std_logic;
      rst_n          : IN     std_ulogic;
      hit            : OUT    std_logic
   );

-- Declarations

END c4_t1_hit_detector ;

--
-- VHDL Architecture alien_game_lib.c4_t1_hit_detector.struct
--
-- Created:
--          by - roope.UNKNOWN (DESKTOP-N94PERP)
--          at - 17:44:20 29.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c4_t1_hit_detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL q     : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_7' of 'adff'
   SIGNAL mw_U_7reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_4' of 'adff'
   q <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_4reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_4reg_cval <= dout3;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'adff'
   hit <= mw_U_7reg_cval;
   u_7seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_7reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_7reg_cval <= dout;
      END IF;
   END PROCESS u_7seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   dout3 <= NOT(dout4) AND NOT(dout5);

   -- ModuleWare code(v1.12) for instance 'U_15' of 'and'
   dout <= NOT(q) AND dout3;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'tor'
   dout4 <= dout1(0) OR dout1(1) OR dout1(2) OR dout1(3) OR dout1(4)
            OR dout1(5) OR dout1(6) OR dout1(7);

   -- ModuleWare code(v1.12) for instance 'U_6' of 'tor'
   dout5 <= dout2(0) OR dout2(1) OR dout2(2) OR dout2(3) OR dout2(4)
            OR dout2(5) OR dout2(6) OR dout2(7);

   -- ModuleWare code(v1.12) for instance 'U_0' of 'xor'
   dout1 <= alien_x_coord XOR bullet_x_coord;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'xor'
   dout2 <= bullet_y_coord XOR alien_y_coord;

   -- Instance port mappings.

END struct;
