-- VHDL Entity alien_game_lib.c4_t4_mux_controller.symbol
--
-- Created:
--          by - roope.UNKNOWN (DESKTOP-N94PERP)
--          at - 19:12:07 29.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t4_mux_controller IS
   PORT( 
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END c4_t4_mux_controller ;

--
-- VHDL Architecture alien_game_lib.c4_t4_mux_controller.tbl
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-708-SPC)
--          at - 13:39:09  2.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF c4_t4_mux_controller IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(data_in)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (data_in = "10000000") THEN
         data_out <= "111";
      ELSIF (data_in = "01000000") THEN
         data_out <= "111";
      ELSIF (data_in = "00100000") THEN
         data_out <= "110";
      ELSIF (data_in = "00010000") THEN
         data_out <= "101";
      ELSIF (data_in = "00001000") THEN
         data_out <= "100";
      ELSIF (data_in = "00000100") THEN
         data_out <= "011";
      ELSIF (data_in = "00000010") THEN
         data_out <= "010";
      ELSIF (data_in = "00000001") THEN
         data_out <= "001";
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
