-- VHDL Entity alien_game_lib.c4_t2_victory_effect_v3.symbol
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-707-SPC)
--          at - 11:20:01 21.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t2_victory_effect_v3 IS
   PORT( 
      clk     : IN     std_logic;
      rst     : IN     std_logic;
      color   : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c4_t2_victory_effect_v3 ;

--
-- VHDL Architecture alien_game_lib.c4_t2_victory_effect_v3.fsm
--
-- Created:
--          by - keskiner.UNKNOWN (HTC219-707-SPC)
--          at - 11:20:01 21.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c4_t2_victory_effect_v3 IS

   TYPE STATE_TYPE IS (
      s0,
      s1,
      s2,
      s3,
      s4,
      s5,
      s6,
      s7,
      s8,
      s9,
      init
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= init;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN s0 => 
            next_state <= s1;
         WHEN s1 => 
            next_state <= s2;
         WHEN s2 => 
            next_state <= s3;
         WHEN s3 => 
            next_state <= s4;
         WHEN s4 => 
            next_state <= s5;
         WHEN s5 => 
            next_state <= s6;
         WHEN s6 => 
            next_state <= s7;
         WHEN s7 => 
            next_state <= s8;
         WHEN s8 => 
            next_state <= s9;
         WHEN s9 => 
            next_state <= s0;
         WHEN init => 
            next_state <= s0;
         WHEN OTHERS =>
            next_state <= init;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      color <= x"0Dff51";
      x_coord <= "00000100";
      y_coord <= "00000100";

      -- Combined Actions
      CASE current_state IS
         WHEN s0 => 
            y_coord <= "00000100";
            x_coord <= "00000100";
         WHEN s1 => 
            y_coord <= "00000100";
            x_coord <= "00100000";
         WHEN s2 => 
            y_coord <= "00010000";
            x_coord <= "00000100";
         WHEN s3 => 
            y_coord <= "00010000";
            x_coord <= "00001000";
         WHEN s4 => 
            y_coord <= "00010000";
            x_coord <= "00010000";
         WHEN s5 => 
            y_coord <= "00010000";
            x_coord <= "00100000";
         WHEN s6 => 
            y_coord <= "00100000";
            x_coord <= "00000100";
         WHEN s7 => 
            y_coord <= "00100000";
            x_coord <= "00100000";
         WHEN s8 => 
            y_coord <= "01000000";
            x_coord <= "00001000";
         WHEN s9 => 
            y_coord <= "01000000";
            x_coord <= "00010000";
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END fsm;
