-- VHDL Entity alien_game_lib.c5_t1_counter.symbol
--
-- Created:
--          by - roope.UNKNOWN (DESKTOP-N94PERP)
--          at - 17:58:41 19.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t1_counter IS
   PORT( 
      clk       : IN     std_logic;
      increment : IN     std_logic;
      max_val   : IN     std_logic_vector (7 DOWNTO 0);
      min_val   : IN     std_logic_vector (7 DOWNTO 0);
      rst_n     : IN     std_logic;
      carry_out : OUT    std_logic;
      val_out   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c5_t1_counter ;

--
-- VHDL Architecture alien_game_lib.c5_t1_counter.struct
--
-- Created:
--          by - roope.UNKNOWN (DESKTOP-N94PERP)
--          at - 17:58:41 19.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c5_t1_counter IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL data_out : std_logic_vector(7 DOWNTO 0);
   SIGNAL din0     : std_logic;
   SIGNAL din1     : std_logic;
   SIGNAL dout     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1    : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2    : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout4    : std_logic;
   SIGNAL dout5    : std_logic;
   SIGNAL dout7    : std_logic;
   SIGNAL q        : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL val_out_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'bit_to_send' of 'adff'
   SIGNAL mw_bit_to_sendreg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'bit_to_send1' of 'adff'
   SIGNAL mw_bit_to_send1reg_cval : std_logic;

   -- Component Declarations
   COMPONENT c2_t3_left_shifter
   PORT (
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t3_left_shifter USE ENTITY alien_game_lib.c2_t3_left_shifter;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'bit_to_send' of 'adff'
   val_out_internal <= mw_bit_to_sendreg_cval;
   bit_to_sendseq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_bit_to_sendreg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_bit_to_sendreg_cval <= dout;
      END IF;
   END PROCESS bit_to_sendseq_proc;

   -- ModuleWare code(v1.12) for instance 'bit_to_send1' of 'adff'
   q <= mw_bit_to_send1reg_cval;
   bit_to_send1seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_bit_to_send1reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_bit_to_send1reg_cval <= dout7;
      END IF;
   END PROCESS bit_to_send1seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   dout1 <= max_val AND val_out_internal;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   dout7 <= increment AND din0;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   din1 <= increment AND NOT(dout4);

   -- ModuleWare code(v1.12) for instance 'U_9' of 'and'
   carry_out <= dout7 AND NOT(q);

   -- ModuleWare code(v1.12) for instance 'U_0' of 'merge'
   dout2 <= din1 & dout4;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(val_out_internal, min_val, data_out, dout2)
   BEGIN
      CASE dout2 IS
      WHEN "00" => dout <= val_out_internal;
      WHEN "01" => dout <= min_val;
      WHEN "10" => dout <= data_out;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'or'
   dout4 <= dout7 OR dout5;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'tor'
   din0 <= dout1(0) OR dout1(1) OR dout1(2) OR dout1(3) OR dout1(4)
           OR dout1(5) OR dout1(6) OR dout1(7);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'tor'
   dout5 <= NOT(val_out_internal(0) OR val_out_internal(1)
            OR val_out_internal(2) OR val_out_internal(3)
            OR val_out_internal(4) OR val_out_internal(5)
            OR val_out_internal(6) OR val_out_internal(7));

   -- Instance port mappings.
   U_2 : c2_t3_left_shifter
      PORT MAP (
         data_in  => val_out_internal,
         data_out => data_out
      );

   -- Implicit buffered output assignments
   val_out <= val_out_internal;

END struct;
