-- VHDL Entity alien_game_lib.c5_t2_single_register.symbol
--
-- Created:
--          by - roope.UNKNOWN (ROOPE-PC)
--          at - 10:35:38 20.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t2_single_register IS
   PORT( 
      clk       : IN     std_logic;
      nullify   : IN     std_logic;
      pix_d     : IN     std_logic_vector (23 DOWNTO 0);
      rst_n     : IN     std_logic;
      write     : IN     std_logic;
      pix_d_out : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c5_t2_single_register ;

--
-- VHDL Architecture alien_game_lib.c5_t2_single_register.struct
--
-- Created:
--          by - roope.UNKNOWN (ROOPE-PC)
--          at - 10:35:38 20.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c5_t2_single_register IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout : std_logic_vector(23 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL pix_d_out_internal : std_logic_vector (23 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(23 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   pix_d_out_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= x"000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         IF (nullify = '1') THEN
            mw_U_0reg_cval <= x"000000";
         ELSE
            mw_U_0reg_cval <= dout;
         END IF;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(pix_d_out_internal, pix_d, write)
   BEGIN
      CASE write IS
      WHEN '0' => dout <= pix_d_out_internal;
      WHEN '1' => dout <= pix_d;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   pix_d_out <= pix_d_out_internal;

END struct;
